# -*- coding: utf-8 -*-
"""3_TFM_Evolve_Punto_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oeYANYL0NC3UqzSe82Ct-BF8f4WydN5W

# TFM - Sistema de apoyo a la planificación hospitalaria basado en datos reales del SNS
## 3. Preparación de los datos (Data Preparation)

Construye la capa **gold** del índice estructural de presión asistencial (patología × CCAA, 2023) a partir de las 8 fuentes reales del INE/Ministerio de Sanidad validadas en la fase de Data Understanding (sección 2).

**Recordatorio de alcance:** ninguna fuente cruza diagnóstico + territorio + tiempo simultáneamente. Esta capa gold usa el **corte transversal 2023** (único año con cruce diagnóstico × CCAA); la serie 2014-2023 pertenece al bloque de tendencia nacional, ya trabajado en el EDA de la sección 2.

Salidas: `gold_presion_asistencial_2023.csv`, `gold_contexto_ccaa_2023.csv`, `diccionario_datos_gold_2023.csv`.

### Paso 0 - Entorno y datos de entrada

Este notebook necesita los 8 ficheros `.xlsx` originales en la misma carpeta de ejecución. En **Google Colab** no están disponibles por defecto: sube los ficheros con la celda siguiente (botón de selección) o móntalos desde Google Drive antes de continuar.
"""

# --- Solo en Google Colab: subir los 8 .xlsx originales ---
import sys
if 'google.colab' in sys.modules:
    from google.colab import files
    print("Selecciona los 8 ficheros .xlsx (Alta_Diagnostico_Provincia, Tablas_CCAA_2023,")
    print("Alta_Motivo_ingreso, Alta_Urgencia_ingreso, Estancia_media, Altas_Diagnostico_principal,")
    print("Actividad_Evolucion_2014-2023, Dotacion_Evolucion_2014-2023):")
    uploaded = files.upload()

!pip install openpyxl -q
import re
from pathlib import Path
import openpyxl
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', 25)
DATA_DIR = Path(".")

"""## 3.1 Selección de tablas y campos finales por dataset

| Fichero | Qué aporta | Nivel | Papel |
|---|---|---|---|
| `Alta_Diagnostico_Provincia.xlsx` | Altas por diagnóstico (capítulo CIE-10) × CCAA | CCAA/provincia, 2023 | **Variable base** — único cruce territorio × diagnóstico disponible |
| `Tablas_CCAA_2023.xlsx` (1.1, 2.1, 4.1, 5.1, 5.2, 6.4) | Hospitales, camas, personal, frecuentación, indicadores de hospitalización, urgencias | CCAA, 2023 | Contexto estructural territorial |
| `Alta_Motivo_ingreso.xlsx` | Traslado y fallecimiento por diagnóstico | Nacional | Contexto por patología |
| `Alta_Urgencia_ingreso.xlsx` | % de ingreso urgente por diagnóstico | Nacional | Contexto por patología |
| `Estancia_media.xlsx` | Estancia media por diagnóstico | Nacional | Contexto por patología |

Se trabaja solo con filas de **nivel capítulo CIE-10** (código de 4 dígitos terminado en `00`, excluyendo `0000`) — 20 capítulos en total, para no duplicar el total al agregar con los subcapítulos.
"""

CHAPTER_NAMES = {
    "0100": "Enfermedades infecciosas y parasitarias", "0200": "Neoplasias",
    "0300": "Enf. sangre / sist. inmunitario", "0400": "Enf. endocrinas, nutricionales y metabólicas",
    "0500": "Trastornos mentales", "0600": "Enf. sistema nervioso", "0700": "Enf. del ojo",
    "0800": "Enf. del oído", "0900": "Enf. sistema circulatorio", "1000": "Enf. sistema respiratorio",
    "1100": "Enf. aparato digestivo", "1200": "Enf. piel y tejido subcutáneo",
    "1300": "Enf. sistema osteomuscular", "1400": "Enf. sistema genitourinario",
    "1500": "Complicaciones embarazo/parto", "1600": "Enf. período perinatal",
    "1700": "Anomalías congénitas", "1800": "Síntomas y signos anormales",
    "1900": "Lesiones y envenenamientos", "2100": "Factores que influyen en el estado de salud",
}

def chapter_rows(rows, start, end, code_col=0):
    """Filas de nivel capítulo (código de 4 dígitos terminado en '00')."""
    out = {}
    for r in rows[start:end]:
        label = r[code_col]
        if not label or not isinstance(label, str):
            continue
        m = re.match(r"^\s*(\d{4})\s+(.*)", label.strip())
        if not m:
            continue
        code, name = m.groups()
        if code.endswith("00") and code != "0000":
            out[code] = (name.strip(), r)
    return out

def _wb_rows(path, sheet):
    wb = openpyxl.load_workbook(DATA_DIR / path, read_only=True, data_only=True)
    return list(wb[sheet].iter_rows(values_only=True))

"""## 3.2 Limpieza: tipado, valores ".." y nulos, normalización de CCAA, snake_case

- **Cabeceras variables por hoja**: se localiza dinámicamente la fila de cabecera de cada hoja de `Tablas_CCAA_2023.xlsx` (de la 3 a la 7 según la tabla).
- **Nombres de CCAA no homogéneos entre ficheros**: `normalize_ccaa()` quita tildes, comas y la `ñ` (**imprescindible**: sin sustituir `ñ→n`, País Vasco y Cataluña no casan con el diccionario canónico) y hace *match* por prefijo.
- **Ceuta y Melilla**: columnas separadas en `Alta_Diagnostico_Provincia`, fila combinada en `Tablas_CCAA_2023` → se agregan como una única unidad territorial en toda la capa gold.
- **Valores `..` (secreto estadístico)**: se tratan como ausentes, nunca como cero.
"""

CCAA_CANON = {
    "andalucia": "Andalucía", "aragon": "Aragón", "asturias": "Asturias, Principado de",
    "balears": "Balears, Illes", "canarias": "Canarias", "cantabria": "Cantabria",
    "castilla y leon": "Castilla y León", "castilla - la mancha": "Castilla - La Mancha",
    "castilla la mancha": "Castilla - La Mancha", "cataluna": "Cataluña",
    "comunitat valenciana": "Comunitat Valenciana", "extremadura": "Extremadura",
    "galicia": "Galicia", "madrid": "Madrid, Comunidad de", "murcia": "Murcia, Región de",
    "navarra": "Navarra, Comunidad Foral de", "pais vasco": "País Vasco", "rioja": "Rioja, La",
    "ceuta y melilla": "Ceuta y Melilla", "ceuta": "Ceuta y Melilla",
}

def normalize_ccaa(raw):
    if not raw or not isinstance(raw, str):
        return None
    s = raw.lower().strip()
    s = (s.replace("á","a").replace("é","e").replace("í","i").replace("ó","o").replace("ú","u")
           .replace("ñ","n").replace(",", "").replace(".", ""))
    s = re.sub(r"\s+", " ", s)
    for key in CCAA_CANON:
        if s.startswith(key):
            return CCAA_CANON[key]
    return None

"""## 3.3 Integración: `Alta_Diagnostico_Provincia` (diagnóstico × CCAA) con `Tablas_CCAA_2023` (dotación/personal/urgencias × CCAA)"""

def load_altas_diagnostico_provincia():
    rows = _wb_rows("Alta_Diagnostico_Provincia.xlsx", "tabla-74901")
    start = end = None
    for i, r in enumerate(rows):
        if r[0] == "Ambos sexos":
            start = i + 1
        elif r[0] == "Hombres" and start is not None:
            end = i; break
    chap = chapter_rows(rows, start, end)

    ccaa_cols = {
        2:"Andalucía", 11:"Aragón", 15:"Asturias, Principado de", 16:"Balears, Illes",
        17:"Canarias", 20:"Cantabria", 21:"Castilla y León", 31:"Castilla - La Mancha",
        37:"Cataluña", 42:"Comunitat Valenciana", 46:"Extremadura", 49:"Galicia",
        54:"Madrid, Comunidad de", 55:"Murcia, Región de", 56:"Navarra, Comunidad Foral de",
        57:"País Vasco", 61:"Rioja, La",
    }
    recs = []
    for code, (name, r) in chap.items():
        for col, ccaa in ccaa_cols.items():
            recs.append({"patologia_cie10": code, "patologia_nombre": CHAPTER_NAMES.get(code, name),
                         "ccaa": ccaa, "altas": r[col]})
        ceuta, melilla = (r[62] or 0), (r[63] or 0)
        recs.append({"patologia_cie10": code, "patologia_nombre": CHAPTER_NAMES.get(code, name),
                     "ccaa": "Ceuta y Melilla", "altas": ceuta + melilla})
    return pd.DataFrame(recs)

df_altas = load_altas_diagnostico_provincia()
print(f"{len(df_altas)} filas = {df_altas.patologia_cie10.nunique()} patologías x {df_altas.ccaa.nunique()} territorios")
df_altas.head()

def read_ccaa_indexed_sheet(path, sheet, header_row_idx, name_col, value_cols):
    rows = _wb_rows(path, sheet)
    out = {}
    for r in rows[header_row_idx:]:
        ccaa = normalize_ccaa(r[name_col])
        if ccaa is None:
            continue
        out.setdefault(ccaa, {})
        for var, col in value_cols.items():
            out[ccaa][var] = r[col]
    return out

path_ccaa = "Tablas_CCAA_2023.xlsx"
hosp = read_ccaa_indexed_sheet(path_ccaa, "1.1", 3, 0,
        {"hospitales_sns":1, "hospitales_privados":2, "hospitales_total":3})
camas = read_ccaa_indexed_sheet(path_ccaa, "2.1", 7, 0,
        {"camas_instaladas_sns":1, "camas_instaladas_total":3, "camas_instaladas_por1000":4,
         "camas_funcionamiento_sns":6, "camas_funcionamiento_total":8,
         "camas_funcionamiento_por1000":9, "pct_camas_sns":10})
personal = read_ccaa_indexed_sheet(path_ccaa, "4.1", 5, 0,
        {"personal_jornada_completa":1, "personal_jornada_parcial":2,
         "personal_vinculado":3, "personal_por1000":6})
freq = read_ccaa_indexed_sheet(path_ccaa, "5.1", 7, 1,
        {"ingresos_total_ccaa":2, "ingresos_por1000":3, "altas_total_ccaa":5,
         "altas_por1000":6, "estancias_total_ccaa":8, "estancias_por1000":9})
# 5.2: se usan los indicadores del subsector Público-SNS como valor representativo de la CCAA
# (concentra entre el 70% y el 100% de las camas en funcionamiento según territorio, ver sección 2)
indic = read_ccaa_indexed_sheet(path_ccaa, "5.2", 4, 0,
        {"estancia_media_sns":1, "ocupacion_sns":2, "rotacion_sns":3, "mortalidad_sns":4,
         "estancia_media_priv":5, "ocupacion_priv":6, "rotacion_priv":7, "mortalidad_priv":8})
urg = read_ccaa_indexed_sheet(path_ccaa, "6.4", 6, 0,
        {"urgencias_total":1, "pct_urgencias_sns":2, "urgencias_por1000":3,
         "pct_urgencias_ingresadas":4, "presion_urgencias":5})

ccaa_list = sorted(hosp.keys())
assert len(ccaa_list) == 18, f"Se esperaban 18 territorios, hay {len(ccaa_list)}"

df_ctx = pd.DataFrame([
    {"ccaa": c, **hosp[c], **camas[c], **personal[c], **freq[c], **indic[c], **urg[c]}
    for c in ccaa_list
])
print(df_ctx.shape, "-", df_ctx.isna().sum().sum(), "nulos")

# Control de coherencia del cruce: relación entre dotación y demanda a nivel CCAA
corr = df_ctx[["camas_funcionamiento_por1000","altas_por1000"]].corr().iloc[0,1]
print(f"Correlación camas/1.000 hab. vs altas/1.000 hab. entre CCAA: {corr:.2f}")
df_ctx.head()

"""**Nota de alcance (ver 3.5):** motivo de alta, urgencia del ingreso y estancia media solo existen a nivel **nacional**, no cruzados con CCAA/provincia. No se estiman a nivel territorial; se incorporan como contexto nacional por patología."""

def load_national_by_chapter(path, sheet, total_col):
    rows = _wb_rows(path, sheet)
    chap = chapter_rows(rows, 8, len(rows))
    return {code: r[total_col] for code, (name, r) in chap.items()}

motivo_total = load_national_by_chapter("Alta_Motivo_ingreso.xlsx", "tabla-74880", 1)
motivo_trasl = load_national_by_chapter("Alta_Motivo_ingreso.xlsx", "tabla-74880", 3)
motivo_fall  = load_national_by_chapter("Alta_Motivo_ingreso.xlsx", "tabla-74880", 4)
urg_urgente  = load_national_by_chapter("Alta_Urgencia_ingreso.xlsx", "tabla-74877", 5)
urg_total    = load_national_by_chapter("Alta_Urgencia_ingreso.xlsx", "tabla-74877", 1)
estancia_nac = load_national_by_chapter("Estancia_media.xlsx", "tabla-74890", 1)

df_nat = pd.DataFrame([{
    "patologia_cie10": code,
    "tasa_traslado_nacional": (motivo_trasl.get(code,0) or 0)/motivo_total[code] if motivo_total.get(code) else None,
    "pct_fallecimiento_nacional": (motivo_fall.get(code,0) or 0)/motivo_total[code] if motivo_total.get(code) else None,
    "pct_urgente_nacional": (urg_urgente.get(code,0) or 0)/urg_total[code] if urg_total.get(code) else None,
    "estancia_media_dias_nacional": estancia_nac.get(code),
} for code in CHAPTER_NAMES])

df_nat.sort_values("tasa_traslado_nacional", ascending=False)

"""## 3.4 Variables derivadas

`tasa_traslado_nacional`, `pct_fallecimiento_nacional`, `pct_urgente_nacional`, `estancia_media_dias_nacional` (a partir del contexto nacional) + `altas_pct_sobre_ccaa` y `altas_por1000hab_camas` (ratios de presión propios del cruce diagnóstico × CCAA). Los ratios de dotación por 1.000 hab. ya vienen normalizados por población en origen y no se recalculan.
"""

df_gold = (df_altas
           .merge(df_ctx, on="ccaa", how="left")
           .merge(df_nat, on="patologia_cie10", how="left"))
df_gold["anio"] = 2023

df_gold["altas_pct_sobre_ccaa"] = df_gold.groupby("ccaa")["altas"].transform(lambda x: x / x.sum())
df_gold["altas_por1000hab_camas"] = df_gold["altas"] / df_gold["camas_funcionamiento_total"]
df_gold["traslados_estimados_nacional"] = df_gold["altas"] * df_gold["tasa_traslado_nacional"]

cols_front = ["anio","ccaa","patologia_cie10","patologia_nombre","altas"]
df_gold = df_gold[cols_front + [c for c in df_gold.columns if c not in cols_front]]

print(df_gold.shape, "-", df_gold.isna().sum().sum(), "nulos")
df_gold.head()

"""## 3.5 Limitación documentada: `Alta_Motivo_ingreso` (traslados/fallecimiento) solo a nivel nacional

Se verifica explícitamente que estas variables no varían entre CCAA para una misma patología — es un hueco real de las fuentes, no se estima.
"""

chk = df_gold[df_gold["patologia_cie10"]=="0500"][["ccaa","tasa_traslado_nacional"]]
print(chk.to_string(index=False))
print("\n¿Varía tasa_traslado_nacional entre CCAA para trastornos mentales?",
      chk["tasa_traslado_nacional"].nunique() > 1, "(debe ser False)")

"""## 3.6 Capa gold final: datasets, diccionario de datos, claves primarias

- `gold_presion_asistencial_2023.csv` — PK `(anio, ccaa, patologia_cie10)`
- `gold_contexto_ccaa_2023.csv` — PK `(ccaa)`
- `diccionario_datos_gold_2023.csv` — diccionario de datos
"""

df_gold.to_csv("gold_presion_asistencial_2023.csv", index=False)
df_ctx.to_csv("gold_contexto_ccaa_2023.csv", index=False)

diccionario = pd.DataFrame({
    "campo": df_gold.columns, "tipo": df_gold.dtypes.astype(str),
    "nulos": df_gold.isna().sum().values, "ejemplo": df_gold.iloc[0].values,
})
diccionario.to_csv("diccionario_datos_gold_2023.csv", index=False)

total = df_gold["altas"].sum()
print(f"Suma de altas en la capa gold: {total:,.0f} (referencia oficial INE 2023: 4.866.745; "
      f"diferencia = {(1 - total/4_866_745)*100:.2f}%, secreto estadístico residual)")

# En Colab: descargar los 3 ficheros generados
if 'google.colab' in sys.modules:
    from google.colab import files as colab_files
    for f in ["gold_presion_asistencial_2023.csv", "gold_contexto_ccaa_2023.csv", "diccionario_datos_gold_2023.csv"]:
        colab_files.download(f)

diccionario

"""## 3.7 Qué se descarta y por qué

| Elemento descartado | Motivo |
|---|---|
| Subcapítulos CIE-10 (código no terminado en `00`) | Evita duplicar el total al agregar |
| Traslado/fallecimiento/urgencia/estancia media por CCAA | No existen en ninguna fuente pública; hueco real, no se estima |
| Años 2020-2021 (bloque de tendencia nacional) | Ruptura estructural pandémica, ver sección 2 |
| Provincias | El contexto de `Tablas_CCAA_2023` no baja de nivel CCAA |
| Sexo como variable de cruce | Se usa el bloque "Ambos sexos"; línea futura en Anexo |

## Validación final antes de pasar a modelado (sección 4)
"""

presion_ccaa = (df_gold.groupby("ccaa")
                .apply(lambda g: g["altas"].sum() / g["camas_funcionamiento_total"].iloc[0])
                .sort_values(ascending=False))

fig, ax = plt.subplots(figsize=(8,5))
presion_ccaa.plot(kind="barh", ax=ax, color="#2b4c7e")
ax.set_xlabel("Altas totales 2023 / camas en funcionamiento")
ax.set_title("Presión estructural agregada por CCAA (altas por cama), 2023")
ax.invert_yaxis()
plt.tight_layout()
plt.show()

print(f"Territorio más presionado: {presion_ccaa.index[0]} ({presion_ccaa.iloc[0]:.1f})")
print(f"Territorio menos presionado: {presion_ccaa.index[-1]} ({presion_ccaa.iloc[-1]:.1f})")
print(f"Ratio máximo/mínimo: {presion_ccaa.iloc[0]/presion_ccaa.iloc[-1]:.2f}")