# -*- coding: utf-8 -*-
"""4_TFM_Evolve_Punto_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xACYIF6MludIjp4cTxu5N_1kJBkdptNw

Preparación de datos - capa gold del índice de presión asistencial
TFM - Sistema de apoyo a la planificación hospitalaria (SNS)

Integra:
  - Alta_Diagnostico_Provincia.xlsx  (altas por diagnóstico x CCAA, 2023)
  - Tablas_CCAA_2023.xlsx            (camas, personal, urgencias x CCAA, 2023)
  - Alta_Motivo_ingreso.xlsx         (tasa traslado/fallecimiento x diagnóstico, nacional)
  - Estancia_media.xlsx              (estancia media x diagnóstico, nacional)

Salida: gold_presion_asistencial_2023.csv + diccionario de datos
"""

import re
import pandas as pd
import openpyxl
import os

DATA_DIR = "."
OUT_DIR = "./gold"
os.makedirs(OUT_DIR, exist_ok=True)

CHAPTER_RE = re.compile(r"^(\d{4})\s+(.*)")

"""0. Diccionario de normalización de nombres de CCAA (nombre tal como aparece en cada fuente -> nombre normalizado snake_case)"""

NORMALIZA_CCAA = {
    # Alta_Diagnostico_Provincia -> normalizado
    "ANDALUCÍA": "andalucia", "ARAGÓN": "aragon", "ASTURIAS, PRINCIPADO DE": "asturias",
    "BALEARS, ILLES": "baleares", "CANARIAS": "canarias", "CANTABRIA": "cantabria",
    "CASTILLA Y LEÓN": "castilla_y_leon", "CASTILLA - LA MANCHA": "castilla_la_mancha",
    "CATALUÑA": "cataluna", "COMUNITAT VALENCIANA": "c_valenciana",
    "EXTREMADURA": "extremadura", "GALICIA": "galicia", "MADRID, COMUNIDAD DE": "madrid",
    "MURCIA, REGIÓN DE": "murcia", "NAVARRA, COMUNIDAD FORAL DE": "navarra",
    "PAÍS VASCO": "pais_vasco", "RIOJA, LA": "la_rioja", "CEUTA": "ceuta_melilla",
    "MELILLA": "ceuta_melilla",
    # Tablas_CCAA_2023 -> normalizado
    # NOTA: la tabla 2.1 del propio fichero usa una redacción distinta para
    # Asturias y Navarra que las tablas 4.1 y 6.4 (ver apartado 2.4/3.2:
    # "Asturias, Principado de" vs. "Asturias, Principado"); se incluyen
    # ambas variantes para que el cruce no pierda esas dos CCAA.
    "Andalucía": "andalucia", "Aragón": "aragon",
    "Asturias, Principado": "asturias", "Asturias, Principado de": "asturias",
    "Balears, Illes": "baleares", "Canarias": "canarias", "Cantabria": "cantabria",
    "Castilla y León": "castilla_y_leon", "Castilla - La Mancha": "castilla_la_mancha",
    "Cataluña": "cataluna", "Comunitat Valenciana": "c_valenciana",
    "Extremadura": "extremadura", "Galicia": "galicia", "Madrid, Comunidad de": "madrid",
    "Murcia, Región de": "murcia",
    "Navarra, C. Foral de": "navarra", "Navarra, Comunidad Foral de": "navarra",
    "País Vasco": "pais_vasco", "Rioja, La": "la_rioja", "Ceuta y Melilla": "ceuta_melilla",
}

""" 1. Alta_Diagnostico_Provincia — altas por capítulo diagnóstico x CCAA (Ceuta y Melilla se agregan en una sola fila para poder cruzar con Tablas_CCAA_2023, que ya las presenta unidas)"""

wb = openpyxl.load_workbook(f"{DATA_DIR}/Alta_Diagnostico_Provincia.xlsx", read_only=True, data_only=True)
ws = wb["tabla-74901"]
rows = list(ws.iter_rows(values_only=True))

CCAA_COLS_RAW = {
    "ANDALUCÍA": 2, "ARAGÓN": 11, "ASTURIAS, PRINCIPADO DE": 15, "BALEARS, ILLES": 16,
    "CANARIAS": 17, "CANTABRIA": 20, "CASTILLA Y LEÓN": 21, "CASTILLA - LA MANCHA": 31,
    "CATALUÑA": 37, "COMUNITAT VALENCIANA": 42, "EXTREMADURA": 46, "GALICIA": 49,
    "MADRID, COMUNIDAD DE": 54, "MURCIA, REGIÓN DE": 55, "NAVARRA, COMUNIDAD FORAL DE": 56,
    "PAÍS VASCO": 57, "RIOJA, LA": 61, "CEUTA": 62, "MELILLA": 63,
}

chapters = []
for i in range(8, 158):
    label = rows[i][0]
    if not label:
        continue
    m = CHAPTER_RE.match(label.strip())
    if m and m.group(1).endswith("00") and m.group(1) != "0000":
        chapters.append((i, m.group(1), m.group(2).strip()))

registros = []
for nombre_raw, col in CCAA_COLS_RAW.items():
    ccaa_norm = NORMALIZA_CCAA[nombre_raw]
    total_ccaa_raw = rows[8][col]
    for i, code, name in chapters:
        altas = rows[i][col]
        registros.append({
            "ccaa": ccaa_norm, "diagnostico_codigo": code, "diagnostico_nombre": name,
            "altas": altas, "_total_ccaa_raw": total_ccaa_raw,
        })

df_altas = pd.DataFrame(registros)
# Agregamos Ceuta+Melilla sumando altas (variable de conteo -> suma correcta)
df_altas_agg = (
    df_altas.groupby(["ccaa", "diagnostico_codigo", "diagnostico_nombre"], as_index=False)
    .agg(altas=("altas", "sum"))
)

"""2. Tablas_CCAA_2023 - camas, personal, urgencias por CCAA"""

wb2 = openpyxl.load_workbook(f"{DATA_DIR}/Tablas_CCAA_2023.xlsx", read_only=True, data_only=True)

# 2.1: camas en funcionamiento (col 8 = TOTAL, col 9 = dotación/1000hab)
ws21 = wb2["2.1"]
rows21 = list(ws21.iter_rows(values_only=True))
camas = {}
for r in rows21[7:25]:
    if not r[0] or r[0] == "TOTAL":
        continue
    ccaa_norm = NORMALIZA_CCAA.get(r[0].replace("*", ""))
    if ccaa_norm:
        camas[ccaa_norm] = {"camas_funcionamiento_total": r[8], "camas_por_1000hab": r[9]}

# 4.1: personal vinculado (col 3 = Personal Vinculado, col 6 = por 1.000 hab)
ws41 = wb2["4.1"]
rows41 = list(ws41.iter_rows(values_only=True))
personal = {}
for r in rows41[5:23]:
    if not r[0] or r[0] == "TOTAL":
        continue
    ccaa_norm = NORMALIZA_CCAA.get(r[0])
    if ccaa_norm:
        personal[ccaa_norm] = {"personal_vinculado_total": r[3], "personal_por_1000hab": r[6]}

# 6.4: urgencias (col1 = N.º, col3 = por 1000hab)
ws64 = wb2["6.4"]
rows64 = list(ws64.iter_rows(values_only=True))
urgencias = {}
for r in rows64[6:24]:
    if not r[0] or r[0] == "TOTAL":
        continue
    ccaa_norm = NORMALIZA_CCAA.get(r[0])
    if ccaa_norm:
        urgencias[ccaa_norm] = {"urgencias_total": r[1], "urgencias_por_1000hab": r[3]}

df_ccaa_estructura = pd.DataFrame(camas).T.join(pd.DataFrame(personal).T).join(pd.DataFrame(urgencias).T)
df_ccaa_estructura.index.name = "ccaa"
df_ccaa_estructura = df_ccaa_estructura.reset_index()

"""3. Alta_Motivo_ingreso - tasa de traslado y fallecimiento (nacional, por diagnóstico)"""

wb3 = openpyxl.load_workbook(f"{DATA_DIR}/Alta_Motivo_ingreso.xlsx", read_only=True, data_only=True)
ws3 = wb3["tabla-74880"]
rows3 = list(ws3.iter_rows(values_only=True))

chapters3 = []
for i in range(8, 160):
    label = rows3[i][0]
    if not label:
        continue
    m = CHAPTER_RE.match(label.strip())
    if m and m.group(1).endswith("00") and m.group(1) != "0000":
        chapters3.append((i, m.group(1)))

motivo = {}
for i, code in chapters3:
    total, curacion, traslado, fallecimiento = rows3[i][1], rows3[i][2], rows3[i][3], rows3[i][4]
    if total:
        motivo[code] = {
            "tasa_traslado_nacional": round(traslado / total * 100, 3),
            "pct_fallecimiento_nacional": round(fallecimiento / total * 100, 3),
        }
df_motivo = pd.DataFrame(motivo).T
df_motivo.index.name = "diagnostico_codigo"
df_motivo = df_motivo.reset_index()

"""4. Estancia_media - estancia media nacional por diagnóstico (columna "total")"""

wb4 = openpyxl.load_workbook(f"{DATA_DIR}/Estancia_media.xlsx", read_only=True, data_only=True)
ws4 = wb4["tabla-74890"]
rows4 = list(ws4.iter_rows(values_only=True))

chapters4 = []
for i in range(8, 160):
    label = rows4[i][0]
    if not label:
        continue
    m = CHAPTER_RE.match(label.strip())
    if m and m.group(1).endswith("00") and m.group(1) != "0000":
        chapters4.append((i, m.group(1)))

estancia = {code: {"estancia_media_nacional": rows4[i][1]} for i, code in chapters4}
df_estancia = pd.DataFrame(estancia).T
df_estancia.index.name = "diagnostico_codigo"
df_estancia = df_estancia.reset_index()

""" 5. Integración: capa gold"""

gold = df_altas_agg.merge(df_ccaa_estructura, on="ccaa", how="left")
gold = gold.merge(df_motivo, on="diagnostico_codigo", how="left")
gold = gold.merge(df_estancia, on="diagnostico_codigo", how="left")

# Variable derivada: peso del diagnóstico sobre el total de altas de su CCAA
altas_totales_ccaa = gold.groupby("ccaa")["altas"].transform("sum")
gold["pct_altas_sobre_ccaa"] = round(gold["altas"] / altas_totales_ccaa * 100, 3)

# Variable derivada: altas por cada 100 camas en funcionamiento de la CCAA
# (aproximación de presión estructural, a nivel de capítulo diagnóstico)
gold["altas_por_100_camas"] = round(gold["altas"] / gold["camas_funcionamiento_total"] * 100, 2)

# Reordenar columnas
cols_order = [
    "ccaa", "diagnostico_codigo", "diagnostico_nombre", "altas", "pct_altas_sobre_ccaa",
    "camas_funcionamiento_total", "camas_por_1000hab", "altas_por_100_camas",
    "personal_vinculado_total", "personal_por_1000hab",
    "urgencias_total", "urgencias_por_1000hab",
    "tasa_traslado_nacional", "pct_fallecimiento_nacional", "estancia_media_nacional",
]
gold = gold[cols_order]

gold.to_csv(f"{OUT_DIR}/gold_presion_asistencial_2023.csv", index=False)

print("Dimensiones de la capa gold:", gold.shape)
print("CCAA incluidas:", gold['ccaa'].nunique())
print("Capítulos diagnósticos incluidos:", gold['diagnostico_codigo'].nunique())
print("\nPrimeras filas:")
print(gold.head(8).to_string())
print("\nValores nulos por columna:")
print(gold.isna().sum())
print("\nGuardado en:", f"{OUT_DIR}/gold_presion_asistencial_2023.csv")