# -*- coding: utf-8 -*-
"""5_TFM_Evolve_punto_04_modelado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJKxVT0_05fs5zHZNZim8nLkAakwGJpU

# TFM - Sistema de apoyo a la planificación hospitalaria basado en datos reales del SNS
## 4. Modelado (Modeling)

Construye el índice estructural de presión asistencial sobre la capa gold de la sección 3 (`gold_presion_asistencial_2023.csv`). Este notebook cubre el **planteamiento, ajuste y explicabilidad** del modelo (4.1 a 4.5); la validación cruzada y la evaluación crítica están en el notebook separado `tfm_05_evaluacion.ipynb`.

Necesita `gold_presion_asistencial_2023.csv` en la misma carpeta (o subirlo con la celda siguiente en Colab).
"""

import sys
if 'google.colab' in sys.modules:
    from google.colab import files
    print("Sube gold_presion_asistencial_2023.csv (generado en la sección 3):")
    uploaded = files.upload()

!pip install scikit-learn shap -q
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import Ridge
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
import shap

pd.set_option('display.max_columns', 20)
df = pd.read_csv('gold_presion_asistencial_2023.csv')
print(df.shape)

"""## 4.1 Planteamiento del índice: variable objetivo, predictoras, y por qué es un modelo de corte transversal

**Variable objetivo:** `altas_por1000hab_camas` — altas de una patología en una CCAA entre las camas en funcionamiento de esa CCAA (mismo índice ya usado como validación visual en la Figura 3.1). No es una etiqueta inventada: es un proxy real y directamente calculable a partir de la capa gold, lo que permite que el índice final sea el resultado de un modelo con pesos aprendidos y justificables, no una fórmula de pesos fijados a criterio propio.

**Predictoras**, en dos niveles (12 variables):

| Nivel | Variables | Varía por |
|---|---|---|
| Patología (nacional) | `tasa_traslado_nacional`, `pct_fallecimiento_nacional`, `pct_urgente_nacional`, `estancia_media_dias_nacional` | Solo por patología (constante en las 18 CCAA, ver 3.5) |
| CCAA (contexto estructural) | `personal_por1000`, `pct_camas_sns`, `presion_urgencias`, `pct_urgencias_ingresadas`, `estancia_media_sns`, `ocupacion_sns`, `rotacion_sns`, `mortalidad_sns` | Solo por CCAA (constante en las 20 patologías) |

**Se excluye explícitamente `altas_pct_sobre_ccaa`** como predictora: comparte el numerador `altas` con la variable objetivo, así que aunque varía a nivel de segmento, es una fuga de información parcial, no una predictora estructural independiente.

**Por qué corte transversal:** el cruce diagnóstico × territorio es una foto única de 2023 (sección 2); no hay dimensión temporal a esa granularidad.

**Aviso metodológico para la validación (sección 5):** las 360 filas no son observaciones independientes — las variables de patología se repiten en 18 CCAA y las de CCAA en 20 patologías. Esto no se resuelve aquí (es responsabilidad del notebook de evaluación), pero condiciona cómo se debe leer cualquier métrica calculada sobre este modelo.
"""

TARGET = "altas_por1000hab_camas"
NATIONAL_FEATS = ["tasa_traslado_nacional","pct_fallecimiento_nacional",
                  "pct_urgente_nacional","estancia_media_dias_nacional"]
TERRITORIAL_FEATS = ["personal_por1000","pct_camas_sns","presion_urgencias",
                      "pct_urgencias_ingresadas","estancia_media_sns","ocupacion_sns",
                      "rotacion_sns","mortalidad_sns"]
FEATS = NATIONAL_FEATS + TERRITORIAL_FEATS
X = df[FEATS].copy()
y = df[TARGET].copy()
print(f"{len(FEATS)} predictoras, {len(df)} observaciones, {X.isna().sum().sum()} nulos")

"""## 4.2 Alternativas de modelo y regla de decisión

| Alternativa | Por qué se plantea | Riesgo a controlar |
|---|---|---|
| **Ridge** (candidato por defecto) | Coeficientes directamente interpretables — el usuario final (dirección médica) necesita poder auditar el índice, no una caja negra | Asume relación lineal entre predictoras y objetivo |
| **Gradient Boosting Regressor** (alternativa de contraste) | Captura interacciones no lineales | Con 360 filas pseudo-replicadas, mayor riesgo de sobreajuste que Ridge |

**Regla de decisión:** se prioriza Ridge salvo que Gradient Boosting aporte una mejora sustancial y verificable en la validación cruzada (ver `tfm_05_evaluacion.ipynb`). Ambos modelos se ajustan aquí sobre el 100% de los datos, ya que este notebook se centra en el modelo final y su explicabilidad, no en su validación.
"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
ridge_full = Ridge(alpha=1.0, random_state=42).fit(X_scaled, y)
gbr_full = GradientBoostingRegressor(n_estimators=200, max_depth=3, learning_rate=0.05,
                                      random_state=42).fit(X, y)
print("Modelos ajustados sobre el 100% de los datos (360 obs).")
print("Nota: la elección entre Ridge y GBR se decide con los resultados de tfm_05_evaluacion.ipynb.")

"""## 4.3 Bloque de tendencia nacional 2014-2023: qué se puede decir y qué no

Con 10 observaciones anuales agregadas a nivel nacional (sin diagnóstico ni CCAA), este bloque se mantiene explícitamente **descriptivo, no predictivo**:

- **Se puede decir:** la magnitud y el sentido de la ruptura 2020-2021, la tasa de crecimiento acumulado pre-pandemia (2014-2019, +2,3%) y post-pandemia (2020-2023, +14,3% relativo pero incompleto), y el desacoplamiento entre el crecimiento de las urgencias (+6,5% sobre 2019) y la práctica estabilidad de la dotación de camas (+1,3% en la década) — ver Figuras 2.5.1 a 2.5.4 (sección 2).
- **No se puede decir con garantías:** una proyección de valores futuros. Diez puntos anuales no ofrecen la resolución necesaria para ajustar un modelo de series temporales con validez estadística ni para un intervalo de predicción fiable. Este bloque aporta contexto de tendencia, no proyección, y no compite con el índice de 4.1.

*(Bloque documental, sin código asociado: reutiliza el EDA ya construido en la sección 2.)*

## 4.4 Variables descartadas y motivo

| Variable / elemento descartado | Motivo |
|---|---|
| `camas_funcionamiento_por1000`, `camas_instaladas_*` como predictoras | Circularidad: ligadas al denominador de la variable objetivo |
| `altas_pct_sobre_ccaa` como predictora | Comparte el numerador `altas` con la variable objetivo — fuga parcial |
| `altas_total_ccaa`, `ingresos_total_ccaa`, `altas_por1000`, `estancias_*` | Miden el mismo volumen de actividad que interviene en la variable objetivo |
| Provincia como nivel de agregación | Ninguna fuente de contexto estructural baja de nivel CCAA (sección 3) |
| Sexo como variable del modelo | Fuera de alcance, misma razón que en 3.7 |
| *Dummies* de `patologia_cie10` / `ccaa` | Con 360 observaciones, 20+18 categóricas sobre 12 continuas dispararía el sobreajuste |
| *Forecasting* a nivel de segmento (patología × CCAA × año) | No existe panel multianual con esa granularidad (sección 2.2) |
| Score de reingreso o derivación multianual | Dependen de fuentes no disponibles (iCMBD, ocupación diaria); Anexo C |

## 4.5 Explicabilidad: SHAP, score 0-100 y factores principales por segmento

Se usa **SHAP (`TreeExplainer`)** sobre el modelo GBR ajustado sobre el 100% de los datos — en modelos de árboles no ofrece una descomposición exacta como Ridge (`coeficiente × valor estandarizado`), pero sí una atribución consistente y comparable entre segmentos.
"""

explainer = shap.TreeExplainer(gbr_full)
shap_values = explainer.shap_values(X)
shap_df = pd.DataFrame(shap_values, columns=FEATS, index=df.index)

imp_shap = shap_df.abs().mean().sort_values(ascending=True)
fig, ax = plt.subplots(figsize=(7,5))
imp_shap.plot(kind="barh", ax=ax, color="#2b4c7e")
ax.set_xlabel("Importancia media |SHAP|")
ax.set_title("Factores principales del índice de presión asistencial (SHAP)")
plt.tight_layout()
plt.savefig("shap_importancia_variables.png", dpi=150, bbox_inches="tight")
plt.show()

print("Importancia SHAP (mayor a menor):")
print(imp_shap.sort_values(ascending=False).round(4).to_string())

print("\nCoeficientes estandarizados Ridge (referencia):")
print(pd.Series(ridge_full.coef_, index=FEATS).sort_values(key=abs, ascending=False).round(3).to_string())

# Score 0-100 y factores principales por segmento, para el dashboard de la sección 6
pred = gbr_full.predict(X)
df["score_presion_0_100"] = 100 * (pred - pred.min()) / (pred.max() - pred.min())

def top_factores(idx, n=2):
    row = shap_df.loc[idx].abs().sort_values(ascending=False)
    return ", ".join(row.index[:n])

df["factores_principales"] = [top_factores(i) for i in df.index]

out_cols = ["ccaa","patologia_nombre","altas_por1000hab_camas","score_presion_0_100","factores_principales"]
print("Top 5 por score de presión:")
print(df[out_cols].sort_values("score_presion_0_100", ascending=False).head(5).to_string(index=False))
print("\nBottom 5 por score de presión:")
print(df[out_cols].sort_values("score_presion_0_100", ascending=False).tail(5).to_string(index=False))

df[["anio","ccaa","patologia_cie10","patologia_nombre","altas_por1000hab_camas",
    "score_presion_0_100","factores_principales"]].to_csv("indice_presion_dashboard.csv", index=False)
print("\nGuardado indice_presion_dashboard.csv")

"""**Lectura:** las 4 variables de perfil clínico nacional concentran la mayor parte de la importancia SHAP (`pct_fallecimiento_nacional` a la cabeza); dentro de las estructurales, `rotacion_sns` y `personal_por1000` son las que más pesan. Si esa contribución territorial es o no robusta al generalizar a CCAA nunca vistas es precisamente lo que evalúa `tfm_05_evaluacion.ipynb`.

## Descarga de resultados de la sección 4
"""

import zipfile
resultados = ["indice_presion_dashboard.csv","shap_importancia_variables.png"]
with zipfile.ZipFile("tfm_seccion4_resultados.zip", "w", zipfile.ZIP_DEFLATED) as zf:
    for f in resultados:
        zf.write(f)
print("Generado tfm_seccion4_resultados.zip con:", resultados)

if "google.colab" in sys.modules:
    from google.colab import files as colab_files
    colab_files.download("tfm_seccion4_resultados.zip")