# -*- coding: utf-8 -*-
"""6_TFM_Evolve_punto_5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1787k9BhDW_rFrJHRBRx7dg0zsOJxpNTC

# TFM - Sistema de apoyo a la planificación hospitalaria basado en datos reales del SNS
## 5. Evaluación (Evaluation)

Valida el índice planteado en `tfm_04_modelado.ipynb` sobre la capa gold de la sección 3 (`gold_presion_asistencial_2023.csv`). Este notebook es independiente y autocontenido: vuelve a definir target y predictoras, y se centra por completo en la **validación cruzada, las métricas frente al baseline y la revisión crítica** (5.1 a 5.5).

Necesita `gold_presion_asistencial_2023.csv` en la misma carpeta (o subirlo con la celda siguiente en Colab).
"""

import sys
if 'google.colab' in sys.modules:
    from google.colab import files
    print("Sube gold_presion_asistencial_2023.csv (generado en la sección 3):")
    uploaded = files.upload()

!pip install scikit-learn -q
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import Ridge
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, GroupKFold
from sklearn.metrics import mean_absolute_error, r2_score

pd.set_option('display.max_columns', 20)
df = pd.read_csv('gold_presion_asistencial_2023.csv')

TARGET = "altas_por1000hab_camas"
NATIONAL_FEATS = ["tasa_traslado_nacional","pct_fallecimiento_nacional",
                  "pct_urgente_nacional","estancia_media_dias_nacional"]
TERRITORIAL_FEATS = ["personal_por1000","pct_camas_sns","presion_urgencias",
                      "pct_urgencias_ingresadas","estancia_media_sns","ocupacion_sns",
                      "rotacion_sns","mortalidad_sns"]
FEATS = NATIONAL_FEATS + TERRITORIAL_FEATS
X = df[FEATS].copy(); y = df[TARGET].copy()
patologia = df["patologia_cie10"].values
ccaa = df["ccaa"].values
print(f"{len(FEATS)} predictoras, {len(df)} observaciones")

"""## 5.1 Estrategia de validación: por qué un K-Fold aleatorio simple no basta

Las 360 filas de la capa gold no son 360 observaciones independientes: las 4 variables de patología se repiten en las 18 CCAA (pseudo-réplica por patología) y las 8 variables de CCAA se repiten en las 20 patologías (pseudo-réplica por CCAA). Un K-Fold aleatorio simple filtraría información de una misma patología o CCAA entre entrenamiento y test.

Se ejecutan por tanto **tres esquemas de validación cruzada** (5 particiones cada uno):

1. **K-Fold aleatorio simple** — referencia inicial; se espera que sobreestime el rendimiento.
2. **GroupKFold por patología** — deja patologías completas fuera; mide si el modelo generaliza a patologías nunca vistas.
3. **GroupKFold por CCAA** — deja comunidades autónomas completas fuera; mide si el contexto estructural territorial generaliza a territorios nunca vistos. **Es la validación que responde directamente a la pregunta central del proyecto:** ¿el territorio aporta información relevante?

No se usa *split* temporal: es un corte transversal sin dimensión temporal en el cruce patología × CCAA.

## 5.2 Métricas y baseline

**Baseline:** para cada *fold* y cada esquema, se calcula la media de `altas_por1000hab_camas` de cada patología usando solo las filas de entrenamiento de ese *fold*, y se usa esa media como predicción para el test — "la media histórica por patología, sin distinguir CCAA" que pide el criterio de éxito del proyecto.
"""

def run_cv(splitter, groups=None, label=""):
    results = {"baseline": [], "ridge": [], "gbr": []}
    splits = splitter.split(X, y, groups) if groups is not None else splitter.split(X)
    for train_idx, test_idx in splits:
        X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
        pat_train, pat_test = patologia[train_idx], patologia[test_idx]

        means = pd.Series(y_train.values, index=pat_train).groupby(level=0).mean()
        y_pred_base = pd.Series(pat_test).map(means).fillna(y_train.mean()).values

        scaler = StandardScaler()
        Xtr_s, Xte_s = scaler.fit_transform(X_train), scaler.transform(X_test)
        ridge = Ridge(alpha=1.0, random_state=42).fit(Xtr_s, y_train)
        y_pred_ridge = ridge.predict(Xte_s)

        gbr = GradientBoostingRegressor(n_estimators=200, max_depth=3, learning_rate=0.05,
                                         random_state=42).fit(X_train, y_train)
        y_pred_gbr = gbr.predict(X_test)

        for name, yp in [("baseline", y_pred_base), ("ridge", y_pred_ridge), ("gbr", y_pred_gbr)]:
            results[name].append((mean_absolute_error(y_test, yp), r2_score(y_test, yp)))

    summary = pd.DataFrame({
        name: {"MAE_medio": np.mean([v[0] for v in vals]), "MAE_std": np.std([v[0] for v in vals]),
               "R2_medio": np.mean([v[1] for v in vals]), "R2_std": np.std([v[1] for v in vals])}
        for name, vals in results.items()
    }).T
    base_mae = summary.loc["baseline","MAE_medio"]
    summary["mejora_vs_baseline_%"] = (1 - summary["MAE_medio"]/base_mae) * 100
    print(f"--- {label} ---")
    print(summary.round(4))
    print()
    return summary

s_kfold = run_cv(KFold(n_splits=5, shuffle=True, random_state=42),
                  label="K-Fold aleatorio simple (referencia, sobreestima)")
s_pat   = run_cv(GroupKFold(n_splits=5), groups=patologia,
                  label="GroupKFold por PATOLOGIA (generaliza a patologias nuevas)")
s_ccaa  = run_cv(GroupKFold(n_splits=5), groups=ccaa,
                  label="GroupKFold por CCAA (generaliza a territorios nuevos -- pregunta central del proyecto)")

for name, s in [("kfold_simple", s_kfold), ("groupkfold_patologia", s_pat), ("groupkfold_ccaa", s_ccaa)]:
    s.to_csv(f"validacion_{name}.csv")

fig, ax = plt.subplots(figsize=(8,5))
comp = pd.DataFrame({
    "K-Fold simple": s_kfold["MAE_medio"],
    "GroupKFold patología": s_pat["MAE_medio"],
    "GroupKFold CCAA": s_ccaa["MAE_medio"],
}).T
comp.plot(kind="bar", ax=ax, color=["#888888","#c0392b","#2b4c7e"])
ax.set_ylabel("MAE medio")
ax.set_title("MAE por modelo y esquema de validación")
plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig("comparacion_esquemas_validacion.png", dpi=150, bbox_inches="tight")
plt.show()

"""## 5.3 Criterio de aceptación — lectura honesta de los tres esquemas

| Esquema | Baseline MAE | GBR MAE | Mejora GBR | Ridge MAE | Mejora Ridge |
|---|---|---|---|---|---|
| K-Fold simple | 0,2659 | 0,2431 | **+8,6%** | 1,1655 | -338% |
| GroupKFold por patología | 1,3532 | 1,2807 | +5,4% (R² negativo en ambos) | 2,2589 | -67% |
| **GroupKFold por CCAA** | 0,2801 | 0,2782 | **+0,7%** | 1,1136 | -298% |

El K-Fold simple **sobreestima** la contribución del territorio (+8,6%) porque filtra información de la misma CCAA entre entrenamiento y test. Bajo la validación correcta (GroupKFold por CCAA), la mejora de GBR sobre el baseline cae a **+0,7% — prácticamente indistinguible del baseline**.

El criterio de éxito del proyecto exige que el modelo mejore sobre el baseline demostrando que el territorio aporta información relevante, sin fijar un umbral numérico estricto. Esa mejora es real pero marginal bajo la validación correcta. **Se acepta el modelo con esta salvedad explícita**: el hallazgo honesto —no la cifra optimista del K-Fold simple— es el resultado central de la revisión crítica (5.4). Si ningún esquema hubiera mostrado mejora, el resultado documentado habría sido el panel descriptivo de la Figura 3.1, sin componente predictivo añadido.

## 5.4 Revisión crítica: ¿el índice sostiene una conclusión real, o solo confirma patrones ya conocidos?

- La **dominancia del perfil clínico de la patología** es el hallazgo más sólido, y a la vez el más limitado: el baseline explica un R² de 0,90-0,91 con K-Fold simple, pero se desploma a **R² negativo** en GroupKFold por patología — el modelo no generaliza a patologías nunca vistas, solo memoriza las ya vistas.
- La **contribución territorial** que en el K-Fold simple parecía real (+8,6%) **se reduce a +0,7% bajo GroupKFold por CCAA**: no hay evidencia sólida de que el contexto estructural de una CCAA permita predecir su presión asistencial en territorios no vistos. El índice conserva su utilidad como panel descriptivo y de *ranking* entre las 18 CCAA y 20 patologías ya conocidas (Figura 3.1), pero no como modelo predictivo con capacidad de generalización territorial demostrada.
- Esta es la revisión crítica que exige el propio criterio de éxito del proyecto: el índice separa patologías con claridad, pero **no separa territorios con evidencia robusta** una vez corregido el sesgo de validación.

## 5.5 Riesgos y alternativas

| Riesgo | Descripción | Tratamiento |
|---|---|---|
| Sobreestimación por fuga entre *folds* | K-Fold aleatorio simple filtra información de la misma patología/CCAA entre train y test | Corregido con GroupKFold por patología y por CCAA |
| Falta de generalización a patologías nuevas | R² negativo en GroupKFold por patología, baseline y GBR | Se documenta como limitación; el índice es un *ranking*, no un clasificador de patologías nuevas |
| Falta de generalización a territorios nuevos | Mejora de GBR casi nula (+0,7%) en GroupKFold por CCAA | Limitación central del proyecto; no se presenta como modelo predictivo territorial validado |
| Confusión entre severidad clínica y capacidad de red | `personal_por1000` bajo puede reflejar menor dotación real o casuística distinta | El modelo no distingue causalidad, solo asociación |
| Bajo volumen en combinaciones poco frecuentes | Celdas pequeñas (Ceuta y Melilla, Rioja) con recuentos bajos | Visible en la varianza entre *folds*; no se corrige artificialmente |

## Descarga de resultados de la sección 5
"""

import zipfile
resultados = ["validacion_kfold_simple.csv","validacion_groupkfold_patologia.csv",
              "validacion_groupkfold_ccaa.csv","comparacion_esquemas_validacion.png"]
with zipfile.ZipFile("tfm_seccion5_resultados.zip", "w", zipfile.ZIP_DEFLATED) as zf:
    for f in resultados:
        zf.write(f)
print("Generado tfm_seccion5_resultados.zip con:", resultados)

if "google.colab" in sys.modules:
    from google.colab import files as colab_files
    colab_files.download("tfm_seccion5_resultados.zip")